version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "80:80"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"