version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "80:80"
    depends_on:
      - frontend
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"